config/routes.rb
GoodStart::Application.routes.draw do

  resources :immunizations
  devise_for :users
  resources :users
  resources :localities
  resources :countries
  resources :menu_items
  resources :surveys
  resources :enrollment_over_times
  resources :school_results
  resources :attendance_results
  resources :attendances
  resources :institutions
  resources :child_profiles
  resources :family_profiles
  resources :articles

  match '/kindergartens'  => 'institutions#index', :category => 105
  match '/schools'  => 'institutions#index', :category => 107
  match '/hotline'  => 'articles#show', :id => 1

  match '/check_survey_number'  => 'surveys#check_survey_number'
  match '/save_mediator_to_session'  => 'surveys#save_mediator_to_session'
  match '/save_locality_id_to_session'  => 'surveys#save_locality_id_to_session'
  match 'surveys/:id/mark_for_delete', :to => 'surveys#mark_for_delete'
  match 'surveys/:id/mark_as_verified', :to => 'surveys#mark_as_verified'
  match 'surveys/mark_for_delete/:id', :to => 'surveys#mark_for_delete'
  match '/institutions/:id/show/:enter_child', :to => 'institutions#show'
  match '/institutions/:id/edit_children', :to => 'institutions#edit_children'
  match "/institutions/set_date_to_session", :to => "institutions#set_date_to_session"
  match "/institutions/show_children_form/:child_id", :to => "institutions#show_children_form"
  match "/family_profiles/update_mini/:id", :to => "family_profiles#update_mini"
  match "/stats_detail", :to => "users#detail"

  
  root :to => "users#show"
  

end

app/models/locality.rb
class Locality < ActiveRecord::Base
  has_many :surveys
  belongs_to :country
  has_many :children, :through => :surveys
  has_many :children_below_seven, :through => :surveys
  has_many :completed_surveys, :class_name => "Survey", :conditions => {:completed => 1}
  has_many :mediators, :class_name => "User", :foreign_key => :locality_id
  has_many :users, :through => :registrations
  has_many :registrations
  
  has_many :children_at_home, :through => :surveys, :conditions =>  {:institution_id => 51}
  
  def full_name
    "#{code}" " - " "#{city}"
  end

  # def completed_surveys
  #   surveys(:conditions => {:completed => 1})
  # end

  def verified?
    verified==1 ? "Yes" : "No"
  end
  
end

app/controllers/localities_controller.rb
class LocalitiesController < ApplicationController
  def index
    @localities = Locality.all
  end
  
  def show
    @locality = Locality.find(params[:id])
  end
  
  def new
    @locality = Locality.new
  end
  
  def create
    @locality = Locality.new(params[:locality])

    if @locality.save
      flash[:notice] = "Successfully created locality."
      redirect_to localities_url
    else
      render :action => 'new'
    end
  end
  
  def edit
    @locality = Locality.find(params[:id])
  end
  
  def update
    @locality = Locality.find(params[:id])
    if @locality.update_attributes(params[:locality])
      flash[:notice] = "Successfully updated locality."
      redirect_to localities_url
    else
      render :action => 'edit'
    end
  end
  
  def destroy
    @locality = Locality.find(params[:id])
    @locality.destroy
    flash[:notice] = "Successfully destroyed locality."
    redirect_to localities_url
  end
end

app/helpers/localities_helper.rb
module LocalitiesHelper
end

app/views/localities/_form.html.haml
#steps
  - semantic_form_for @locality,:html => {:class => 'form'} do |f|
    - f.inputs 'Locality', :id => "locality", :class => 'step' do
      = f.input :code
      = f.input :city
      = f.input :country
      -if ['L','A'].include? current_user.category
        = f.input :survey_count, :input_html => { :size => 2 }
      = f.buttons

app/views/localities/edit.html.haml
- title "Edit Locality"

= render 'form'

%p
  = link_to "Show", locality_path(@locality)
  |
  = link_to "View All", localities_path

app/views/localities/index.html.haml
- title "Localities"

%table
  %tr
    %th Country
    %th Code
    %th City
    %th 

  - for locality in @localities
    %tr
      %td= locality.country_id
      %td= locality.code
      %td= locality.city
      / %td= link_to 'Show', locality
      %td= link_to 'Edit', edit_locality_path(locality)
      / %td= link_to 'Destroy', locality, :confirm => 'Are you sure?', :method => :delete

.commit
  %p= link_to t("New Locality"), new_locality_path

app/views/localities/new.html.haml
- title "New Locality"

= render 'form'

%p= link_to "Back to List", localities_path

app/views/localities/show.html.haml
.show
  - title "Locality"

  %p
    %strong Country:
    = @locality.country_id
  %p
    %strong Code:
    = @locality.code
  %p
    %strong City:
    = @locality.city

  %p
    = link_to "Edit", edit_locality_path(@locality)
    |
    = link_to "Destroy", @locality, :confirm => 'Are you sure?', :method => :delete
    |
    = link_to "View All", localities_path