config/routes.rb
GoodStart::Application.routes.draw do

  resources :immunizations
  devise_for :users
  resources :users
  resources :localities
  resources :countries
  resources :menu_items
  resources :surveys
  resources :enrollment_over_times
  resources :school_results
  resources :attendance_results
  resources :attendances
  resources :institutions
  resources :child_profiles
  resources :family_profiles
  resources :articles

  match '/kindergartens'  => 'institutions#index', :category => 105
  match '/schools'  => 'institutions#index', :category => 107
  match '/hotline'  => 'articles#show', :id => 1

  match '/check_survey_number'  => 'surveys#check_survey_number'
  match '/save_mediator_to_session'  => 'surveys#save_mediator_to_session'
  match '/save_locality_id_to_session'  => 'surveys#save_locality_id_to_session'
  match 'surveys/:id/mark_for_delete', :to => 'surveys#mark_for_delete'
  match 'surveys/:id/mark_as_verified', :to => 'surveys#mark_as_verified'
  match 'surveys/mark_for_delete/:id', :to => 'surveys#mark_for_delete'
  match '/institutions/:id/show/:enter_child', :to => 'institutions#show'
  match '/institutions/:id/edit_children', :to => 'institutions#edit_children'
  match "/institutions/set_date_to_session", :to => "institutions#set_date_to_session"
  match "/institutions/show_children_form/:child_id", :to => "institutions#show_children_form"
  match "/family_profiles/update_mini/:id", :to => "family_profiles#update_mini"
  match "/stats_detail", :to => "users#detail"

  
  root :to => "users#show"
  

end

app/models/school_result.rb
class SchoolResult < ActiveRecord::Base
  belongs_to :child, :class_name => "ChildProfile"
  belongs_to :institution
end

app/controllers/school_results_controller.rb
class SchoolResultsController < ApplicationController
  
  def index
    @school_results = SchoolResult.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @school_results }
    end
  end

  def show
    @school_result = SchoolResult.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @school_result }
    end
  end

  def new
    unless params[:child_id].blank?
      child = ChildProfile.find(params[:child_id])
      @school_result = SchoolResult.new(:child_id => params[:child_id], :institution_id => child.institution_id)
    else
      render :text => 'No Child ID provided!'
    end

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @school_result }
    end
  end

  def edit
    @school_result = SchoolResult.find(params[:id])
  end

  def create
    @school_result = SchoolResult.new(params[:school_result])
    @school_result.created_by =  current_user.id

    respond_to do |format|
      if @school_result.save
        format.html { redirect_to(school_results_url, :notice => 'School result was successfully created.') }
        format.xml  { render :xml => @school_result, :status => :created, :location => @school_result }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @school_result.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
    @school_result = SchoolResult.find(params[:id])

    respond_to do |format|
      if @school_result.update_attributes(params[:school_result])
        format.html { redirect_to(school_results_url, :notice => 'School result was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @school_result.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @school_result = SchoolResult.find(params[:id])
    @school_result.destroy

    respond_to do |format|
      format.html { redirect_to(school_results_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/school_results_helper.rb
module SchoolResultsHelper
end

app/views/school_results/_form.html.haml
#steps
  - semantic_form_for @school_result, :html => {:name => 'school_result', :class => 'form', :id => 'edit_survey_1'} do |f|
    - f.inputs t("1 Test before primary school"), :id => "imunization", :class => 'step' do
      = f.error_messages
      = f.input :child, :input_html => { :disabled => 'disabled' }
      = f.input :child_id, :as => :hidden, :wrapper_html => {:style => 'visibility:hidden;'}
      / = f.input :survey_date, :start_year => 2010, :end_year => 2012
      = f.input :institution, :input_html => { :disabled => 'disabled' } #, :as => :radio, :collection => MenuItem.immunization
      = f.input :test_before_school, :as => :radio, :collection => MenuItem.classic
      = f.input :test_before_school_result, :as => :radio, :collection => MenuItem.school_result_tests,
        :input_html => { :onclick => 'display_switch(this,"145","school_result_test_before_school_result_other_input");'}

      / = f.input :school_mother, :as => :radio, :collection => MenuItem.school_type.order(:position), 
      /   :input_html => { :onclick => 'display_switch(this,"145","survey_school_mother_other_input");'}
      /   
      / = f.input :school_mother_other, :as => :string, :input_html => {:size => 30}, :wrapper_html => {:style => @school_result.test_before_school_result==145 ? "display:;" : "display:none;"} 

      = f.input :test_before_school_result_other, :as => :string, :input_html => {:size => 30}, :wrapper_html => {:style => @school_result.test_before_school_result==145 ? "display:;" : "display:none;"} 
      
      - if @school_result.child.institution.code_id == 107 or @school_result.child.institution.code_id == 108
        = f.input :proceeded_to_next_year, :as => :radio, :collection => MenuItem.classic_reduced
        = #f.input :institution_id, :collection => Institution.find(:all, :order => "name", :conditions => ['id=51 or locality_id=?',@survey.locality_id])
      
        = f.input :average_school_marks_midterm_10_11
        = f.input :average_school_marks_yearend_10_11
        = f.input :average_school_marks_midterm_11_12
    = f.buttons

app/views/school_results/edit.html.haml
%h1 Editing school_result

= render 'form'

= link_to 'Show', @school_result
\|
= link_to 'Back', school_results_path

app/views/school_results/index.html.haml
- title t("School results")

%table
  %tr
    / %th=# t('Child')
    %th
      = t('Name')
      \–
      = t('Date')
    %th= t('Test before school')
    %th= t('Test result')
    %th= t('Marks 10/11')
    %th= t('Marks end 10/11')
    %th= t('Marks 11/12')
  
  - current_user.localities.each do |l|
    %tr
      %td
        %strong= l.full_name
    - l.children.where("institution_id = 51 and date_of_birth < '2005-09-01'").each do |ch|
      %tr
        %td{:style=>'padding-left:30px;'}
          = link_to ch.full_name, new_school_result_path(:child_id => ch.id)
          / = ch.date_of_birth
        - ch.school_results.each do |chi|
          %tr
            / %td= link_to chi.full_name, edit_immunization_path(chi)
            %td{:style=>'padding-left:50px;'}= link_to chi.created_at.to_s(:db), edit_school_result_path(chi)
            / %td= chi.created_at.to_s(:db)
            %td= MenuItem.find(chi.test_before_school).name_en
            %td= MenuItem.find(chi.test_before_school_result).name_en
            %td= chi.average_school_marks_midterm_10_11
            %td= chi.average_school_marks_yearend_10_11
            %td= chi.average_school_marks_midterm_11_12
      
  - current_user.institutions.each do |i|
    - if i.has_children?
      %tr
        %td
          %strong= i.name
          = '(' "#{i.children.size}" ')'

      - i.children.where("date_of_birth < '2005-09-01'").each do |ch|
        %tr
          %td{:style=>'padding-left:30px;'}
            = link_to ch.full_name, new_school_result_path(:child_id => ch.id)
            / = ch.date_of_birth
          - ch.school_results.each do |chi|
            %tr
              / %td= link_to chi.full_name, edit_immunization_path(chi)
              %td{:style=>'padding-left:50px;'}= link_to chi.created_at.to_s(:db), edit_school_result_path(chi)
              / %td= chi.created_at.to_s(:db)
              %td= MenuItem.find(chi.test_before_school).name_en
              %td= MenuItem.find(chi.test_before_school_result).name_en
              %td= chi.average_school_marks_midterm_10_11
              %td= chi.average_school_marks_yearend_10_11
              %td= chi.average_school_marks_midterm_11_12
            
/ Month, Year (ako čas zberu údajov), Obligatory vaccinations(možnosti: all/some/none/unknown), BCG, DTP, Hib, VHB/HEP B, IPV/VPi, PCV, MMR/ROR (POZOR, toto je už upravený zoznam) - pri týchto yes/no/?

.commit
  %p= link_to t('Add School result'), new_school_result_path

app/views/school_results/new.html.haml
%h1 New school_result

= render 'form'

= link_to 'Back', school_results_path

app/views/school_results/show.html.haml
.show
  %p#notice= notice


  = link_to 'Edit', edit_school_result_path(@school_result)
  \|
  = link_to 'Back', school_results_path