config/routes.rb
GoodStart::Application.routes.draw do

  resources :immunizations
  devise_for :users
  resources :users
  resources :localities
  resources :countries
  resources :menu_items
  resources :surveys
  resources :enrollment_over_times
  resources :school_results
  resources :attendance_results
  resources :attendances
  resources :institutions
  resources :child_profiles
  resources :family_profiles
  resources :articles

  match '/kindergartens'  => 'institutions#index', :category => 105
  match '/schools'  => 'institutions#index', :category => 107
  match '/hotline'  => 'articles#show', :id => 1

  match '/check_survey_number'  => 'surveys#check_survey_number'
  match '/save_mediator_to_session'  => 'surveys#save_mediator_to_session'
  match '/save_locality_id_to_session'  => 'surveys#save_locality_id_to_session'
  match 'surveys/:id/mark_for_delete', :to => 'surveys#mark_for_delete'
  match 'surveys/:id/mark_as_verified', :to => 'surveys#mark_as_verified'
  match 'surveys/mark_for_delete/:id', :to => 'surveys#mark_for_delete'
  match '/institutions/:id/show/:enter_child', :to => 'institutions#show'
  match '/institutions/:id/edit_children', :to => 'institutions#edit_children'
  match "/institutions/set_date_to_session", :to => "institutions#set_date_to_session"
  match "/institutions/show_children_form/:child_id", :to => "institutions#show_children_form"
  match "/family_profiles/update_mini/:id", :to => "family_profiles#update_mini"
  match "/stats_detail", :to => "users#detail"

  
  root :to => "users#show"
  

end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :localities
end

app/models/family_profile.rb
class FamilyProfile < ActiveRecord::Base
  has_many :children, :class_name => 'ChildProfile', :foreign_key => :family_id
  belongs_to :survey
  accepts_nested_attributes_for :survey
  belongs_to :creator, :foreign_key => :created_by, :class_name => 'User'
  has_many :surveys, :foreign_key => :family_id
#  validates_presence_of :number_of_children
  
  def full_household_in_settlement
    if household_in_settlement == 1
      'yes'
    else
      'no'
    end
  end

  def self.columns_for_output
    ["survey_id", "family_name", "non_formal_education", "workshops_on_education", "parental_involment_in_preschool"] 
  end
end

app/controllers/family_profiles_controller.rb
class FamilyProfilesController < ApplicationController
  def index
    if current_user.category == 'A'
      @family_profiles = FamilyProfile.all
    else
      if current_user.localities.blank?
        @family_profiles = current_user.families.order(:family_name)
      else
        @family_profiles = FamilyProfile.where(:locality_id => current_user.locality_ids)
      end
    end
  end
  
  def show
    @family_profile = FamilyProfile.find(params[:id])
  end
  
  def new
    @family_profile = FamilyProfile.new
  end
  
  def create
    @family_profile = FamilyProfile.new(params[:family_profile])
    @family_profile.created_by =  current_user.id

    if @family_profile.save
      flash[:notice] = "Successfully created family profile."
      redirect_to family_profiles_path
    else
      render :action => 'new'
    end
  end
  
  def edit
    @family_profile = FamilyProfile.find(params[:id])
  end
  
  def update
    @family_profile = FamilyProfile.find(params[:id])
    if @family_profile.update_attributes(params[:family_profile])
      flash[:notice] = "Successfully updated family profile."
      redirect_to family_profiles_path
    else
      render :action => 'edit'
    end
  end
  
  def update_mini
    @family_profile = FamilyProfile.find(params[:id])
    if params[:non_formal_education] == "1"
      if @family_profile.non_formal_education == 1
        @family_profile.non_formal_education = 0
      else
        @family_profile.non_formal_education = 1
      end
    end
    if params[:workshops_on_education] == "1"
      if @family_profile.workshops_on_education == 1
        @family_profile.workshops_on_education = 0
      else
        @family_profile.workshops_on_education = 1
      end
    end
    if params[:parental_involment_in_preschool] == "1"
      if @family_profile.parental_involment_in_preschool == 1
        @family_profile.parental_involment_in_preschool = 0
      else
        @family_profile.parental_involment_in_preschool = 1
      end
    end
    @family_profile.save
    redirect_to :action => 'index'
  end
  
  def destroy
    @family_profile = FamilyProfile.find(params[:id])
    @family_profile.destroy
    flash[:notice] = "Successfully destroyed family profile."
    redirect_to family_profiles_url
  end
end

app/helpers/family_profiles_helper.rb
module FamilyProfilesHelper

  def status_non_formal_education(non_formal_education)
    unless non_formal_education.nil?
      non_formal_education == 1 ? I18n.t('Yes') : I18n.t('No')
    else
      raw('<span class="red">?</span>')
    end
  end

  def status_workshops_on_education(workshops_on_education)
    unless workshops_on_education.nil?
      workshops_on_education == 1 ? I18n.t('Yes') : I18n.t('No')
    else
      raw('<span class="red">?</span>')
    end
  end

  def status_parental_involment_in_preschool(parental_involment_in_preschool)
    unless parental_involment_in_preschool.nil?
      parental_involment_in_preschool == 1 ? I18n.t('Yes') : I18n.t('No')
    else
      raw('<span class="red">?</span>')
    end
  end

end

app/views/family_profiles/_form.html.haml
#steps
  - semantic_form_for @family_profile,:html => {:class => 'form'} do |f|
    = f.error_messages
    - f.inputs t("Family Profile"), :id => "family_profile", :class => 'step' do
      = f.input :family_name
      %li{:class=>'numeric optional'}
        %label
          = t("22 Fathers age")
          = @family_profile.surveys.first.fathers_age
      / = f.input :fathers_age, :input_html => { :size => 2 }
      %li{:class=>'numeric optional'}
        %label
          = t("23 Mothers age")
          = @family_profile.surveys.first.mothers_age
      / = f.input :mothers_age, :input_html => { :size => 2 }
      %li{:class=>'numeric optional'}
        %label
          = t("24 Number of children")
          = @family_profile.surveys.first.number_of_all_children
      / = f.input :number_of_children, :input_html => { :size => 2 }
      %li{:class=>'numeric optional'}
        %label
          = t("25 Number of children below seven")
          = @family_profile.surveys.first.number_of_children_below_seven
      / = f.input :number_of_children_below_seven, :input_html => { :size => 2 }
      %li{:class=>'numeric optional'}
        %label
          = t("26 Household in settlement")
          = @family_profile.surveys.first.separated_settlement == 45 ? t("Yes") : t("No")
      / = f.input :household_in_settlement, :as => :radio
      = f.buttons
      
    %fieldset.step
      %div
        %span Deti
      %ol
        - @family_profile.children.each do |ch|

          %li.string.optional
            %label= link_to ch.full_name, edit_child_profile_path(ch)

app/views/family_profiles/edit.html.haml
%h1= t('You are editing family') + @family_profile.family_name

= render 'form'
   
.commit
  = link_to t("View All"), family_profiles_path

app/views/family_profiles/index.html.haml
- title t("Families")

%table
  %tr
    %th{:width=>80}= t('Survey No')
    %th{:width=>120}= t('Family name')
    %th= t('Fathers age')
    %th= t('Mothers age')
    %th= t('Number of children')
    %th= t('Number of children below seven')
    %th= t('Non Formal Education')
    - unless (current_user.locality_ids & [8]).empty?
      %th= t('Workshops on education/health')
    - unless (current_user.locality_ids & [1,15,16,17,18,19]).empty?
      %th= t('Parental Involvement in Preschool')

  - for family_profile in @family_profiles
    %tr.row
      %td= family_profile.survey.number unless family_profile.survey.blank?
      %td= link_to family_profile.family_name, edit_family_profile_path(family_profile)
      %td= family_profile.survey.fathers_age
      %td= family_profile.survey.mothers_age
      %td= family_profile.survey.number_of_all_children
      %td= family_profile.survey.number_of_children_below_seven
      %td= link_to(status_non_formal_education(family_profile.non_formal_education), '/family_profiles/update_mini/' + family_profile.id.to_s + '?non_formal_education=1')
      - unless (current_user.locality_ids & [8]).empty?
        %td= link_to(status_workshops_on_education(family_profile.workshops_on_education), '/family_profiles/update_mini/' + family_profile.id.to_s + '?workshops_on_education=1')
      - unless (current_user.locality_ids & [1,15,16,17,18,19]).empty?
        %td= link_to(status_parental_involment_in_preschool(family_profile.parental_involment_in_preschool), '/family_profiles/update_mini/' + family_profile.id.to_s + '?parental_involment_in_preschool=1')

      / workshops_on_education
      / parental_involment_in_preschool
      / %td= family_profile.full_household_in_settlement
      / %td= family_profile.comment
      / %td= link_to 'Show', family_profile
      / %td= link_to t('Edit'), edit_family_profile_path(family_profile)
      / %td= link_to t('Destroy'), family_profile, :confirm => t('Are you sure?'), :method => :delete

/ .commit
/   %p= link_to t("Add Family"), new_family_profile_path

app/views/family_profiles/new.html.haml
- title t("Adding Family")

= render 'form'

.commit
  %p= link_to t("Back to List"), family_profiles_path

app/views/family_profiles/show.html.haml
.show
  - title t("Family")

  %p
    %strong= t('Survey:')
    = @family_profile.survey_id
  %p
    %strong= t('Created By:')
    = @family_profile.created_by
  %p
    %strong= t('Family Name:')
    = @family_profile.family_name
  / %p
  /   %strong= t('Fathers Age:')
  /   = @family_profile.fathers_age
  / %p
  /   %strong= t('Mothers Age:')
  /   = @family_profile.mothers_age
  / %p
  /   %strong= t('Number Of Children:')
  /   = @family_profile.number_of_children
  / %p
  /   %strong= t('Number Of Children Below Seven:')
  /   = @family_profile.number_of_children_below_seven
  / %p
  /   %strong= t('Household In Settlement:')
  /   = @family_profile.household_in_settlement
  / %p
  /   %strong= t('Comment:')
  /   = @family_profile.comment

  .commit
    %p
      = link_to t("View All"), family_profiles_path