config/routes.rb
GoodStart::Application.routes.draw do

  resources :immunizations
  devise_for :users
  resources :users
  resources :localities
  resources :countries
  resources :menu_items
  resources :surveys
  resources :enrollment_over_times
  resources :school_results
  resources :attendance_results
  resources :attendances
  resources :institutions
  resources :child_profiles
  resources :family_profiles
  resources :articles

  match '/kindergartens'  => 'institutions#index', :category => 105
  match '/schools'  => 'institutions#index', :category => 107
  match '/hotline'  => 'articles#show', :id => 1

  match '/check_survey_number'  => 'surveys#check_survey_number'
  match '/save_mediator_to_session'  => 'surveys#save_mediator_to_session'
  match '/save_locality_id_to_session'  => 'surveys#save_locality_id_to_session'
  match 'surveys/:id/mark_for_delete', :to => 'surveys#mark_for_delete'
  match 'surveys/:id/mark_as_verified', :to => 'surveys#mark_as_verified'
  match 'surveys/mark_for_delete/:id', :to => 'surveys#mark_for_delete'
  match '/institutions/:id/show/:enter_child', :to => 'institutions#show'
  match '/institutions/:id/edit_children', :to => 'institutions#edit_children'
  match "/institutions/set_date_to_session", :to => "institutions#set_date_to_session"
  match "/institutions/show_children_form/:child_id", :to => "institutions#show_children_form"
  match "/family_profiles/update_mini/:id", :to => "family_profiles#update_mini"
  match "/stats_detail", :to => "users#detail"

  
  root :to => "users#show"
  

end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController

  def index
    # if current_user.category == 'A'
    #   @surveys = Survey.all
    # elsif current_user.category == 'L'
      # @surveys = Survey.find(:all, :conditions => "locality_id in(" + current_user.localities + ")")
      @incomplete_surveys = current_user.my_surveys.where('completed is null')
      @completed_surveys = current_user.my_surveys.where('completed = 1')
    # else
    # @columns = []
     # @surveys = Survey.where(:completed => 1).limit(5)
     if current_user.category == 'A'
       if params[:locality_id]
         @children = ChildProfile.where(:locality_id => params[:locality_id])
       else
         @children = ChildProfile.where(:locality_id => [9,10,11,12,13])
       end
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @surveys }
      format.xls
    end
  end

  def show
    @survey = Survey.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  def new
    @survey = Survey.new
    @survey.family = FamilyProfile.new(:created_by => current_user.id)
    # 3.times {@survey.children.build}
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @survey }
    end
  end

  def edit
    @survey = Survey.find(params[:id])
    # tu uz je params[:step] navysena o 1, ako som to urobil pri redirecte v UPDATE
    session[:survey_mediator_survey_counter] = @survey.mediator_survey_counter
    session[:mediator] = @survey.interviewer_id
    if current_user.id == @survey.created_by or (current_user.localities.include? @survey.locality) or current_user.category == 'A'
      @step = params[:step].blank? ? 1 : params[:step]
      if params[:step] == "3"
        # if @survey.family.blank?
        #   @survey.family = FamilyProfile.new(:survey_id => @survey.id)
        # end
        # diff = @survey.children.size - @survey.number_of_children_below_seven
        # if diff > 0
        #   diff_children = diff.times{ ChildProfile.new(:created_by => current_user.id, :family_id => @survey.family_id, :locality_id => @survey.locality_id) }
        # end
        # logger.info 'diff<<<<<<<<<<<<<<<' + diff_children.inspect
        # logger.info 'db <<<<<<<<<<<<<<< ' + @survey.number_of_children_below_seven.to_s
        # logger.info 'children <<<<<<<<<<<<<<< ' + @survey.children.size.to_s
        if @survey.children.size == 0 
          @survey.number_of_children_below_seven.times {@survey.children.build(:created_by => current_user.id, :family_id => @survey.family_id, :locality_id => @survey.locality_id)}
        else
          (@survey.number_of_children_below_seven - @survey.children.size).times {@survey.children.build(:created_by => current_user.id, :family_id => @survey.family_id, :locality_id => @survey.locality_id)}
        end
        # logger.info 'children new >>>> ' + @survey.children.size.to_s
        # unless notice=='Institution was successfully created.'
        #   @survey.number_of_children_below_seven.times {@survey.children.build(:family_id => @survey.family_id)}
        # end
      end
    else
      render :text => 'You cannot edit this survey, because you did not create it.'
    end
  end

  def create
    # verify whether survey with this interviewer_id and location_id already exists / for doubleclickers
    @exists_survey_with_given_mediator_survey_counter_and_location = Survey.where(:mediator_survey_counter  => params[:survey][:mediator_survey_counter], :interviewer_id => params[:survey][:interviewer_id], :locality_id => params[:survey][:locality_id]).first
    unless @exists_survey_with_given_mediator_survey_counter_and_location.blank?
      @survey = Survey.new(params[:survey])
      @survey.family = FamilyProfile.new(:created_by => current_user.id)
      @survey.created_by = current_user.id
      redirect_to surveys_url, :notice => t('This survey was already saved. Please click Submit Button only once. Select survey from the list below.')
    else
      @survey = Survey.new(params[:survey])
      @survey.created_by = current_user.id
      @survey.current_step = 2

      respond_to do |format|
        if @survey.save
          @survey.family.update_attributes(:survey_id => @survey.id,:locality_id => @survey.locality_id)
          format.html { redirect_to(edit_survey_url(@survey)+'?step='+(params[:step]), :notice => 'Survey was successfully saved.') }
          format.xml  { render :xml => @survey, :status => :created, :location => @survey }
        else
          format.html { render :action => "new", :step => 1 }
          format.xml  { render :xml => @survey.errors, :status => :unprocessable_entity }
        end
      end
    end
  end

  def update
    @survey = Survey.find(params[:id])
    unless params[:commit] == t('Add New Institution')
      if params[:step]
        unless @survey.current_step > params[:step].to_i
          @survey.current_step = params[:step]
        end
      end
    end

    if params[:commit] == t('Save and Mark Survey as Completed')
      @survey.completed = 1
      if @survey.locality.survey_count == @survey.locality.completed_surveys.count + 1
        UserMailer.number_reached(current_user,@survey).deliver  
        UserMailer.number_reached(current_user.boss,@survey).deliver  unless current_user.boss.blank?
      end      
      UserMailer.new_survey(current_user,@survey).deliver  
    end

    respond_to do |format|
      if @survey.update_attributes(params[:survey])
        session[:survey_mediator_survey_counter] = nil
        session[:mediator] = nil
        @survey.family.update_attributes(:locality_id => @survey.locality_id)
        if params[:commit] == t('Add New Institution')
          format.html { redirect_to(new_institution_path(:origin_id=>@survey.id))}
        elsif params[:commit] == t("Save and Next")
          format.html { redirect_to(edit_survey_url(@survey)+'?step='+(params[:step].to_i+1).to_s, :notice => t('Survey was successfully updated.')) }
        elsif params[:commit] == t("Save and Add New Survey")
          format.html { redirect_to new_survey_url, :notice => t('Survey was successfully updated.') }
        elsif params[:commit] == t("Save and Mark Survey as Completed")
          format.html { redirect_to surveys_url, :notice => t('Survey was saved and marked as completed') }
        else
          format.html { redirect_to(edit_survey_url(@survey)+'?step='+params[:step].to_s, :notice => t('Survey was successfully updated.')) }
          format.xml  { head :ok }
        end
      else
        format.html { redirect_to(edit_survey_url(@survey)+'?step='+params[:step], :notice => t('There was a problem to save data.')) }
      end
    end

  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to(surveys_url) }
      format.xml  { head :ok }
    end
  end
  
  def check_survey_number
    session[:survey_mediator_survey_counter] = params[:survey][:mediator_survey_counter]
    unless params[:s].blank?
      @survey = Survey.find(params[:s])
      @survey_with_given_mediator_survey_counter = Survey.where(:mediator_survey_counter  => params[:survey][:mediator_survey_counter], :interviewer_id => session[:mediator], :locality_id => session[:locality_id]).first
      if @survey_with_given_mediator_survey_counter
        number_exists = (@survey.id == @survey_with_given_mediator_survey_counter.id ? nil : @survey_with_given_mediator_survey_counter)
      else
        number_exists = nil
      end
    else
      number_exists = Survey.where(:mediator_survey_counter  => params[:survey][:mediator_survey_counter], :interviewer_id => session[:mediator], :locality_id => session[:locality_id])
    end
    if number_exists.blank? 
      render :text => 'true'
    else
      render :text => 'false'
    end
  end

  def mark_as_verified
    if params[:id]
      @survey = Survey.find(params[:id])
      @survey.update_attributes(:verified => 1)
      UserMailer.new_survey(current_user,@survey).deliver  
      redirect_to surveys_url
    else
      render :text => 'no id provided'
    end
  end

  def mark_for_delete
    if params[:id]
      @survey = Survey.find(params[:id])
      if @survey.marked_for_delete.blank?
        @survey.update_attributes(:marked_for_delete => 1)
      else
        @survey.update_attributes(:marked_for_delete => nil)
      end
      redirect_to surveys_url
    else
      render :text => 'no id provided'
    end
  end
  
  def save_locality_id_to_session
    session[:locality_id] = params[:survey][:locality_id]
    unless params[:s].blank?
      @survey = Survey.find(params[:s])
    end
    render :text => 'true'
    
  end
  
  def save_mediator_to_session
    session[:mediator] = params[:survey][:interviewer_id]
    unless params[:s].blank?
      @survey = Survey.find(params[:s])
    end
    render :text => 'true'
  end

end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form_10.html.haml
#steps
  - semantic_form_for @survey, :html => {:name => 'survey',:class => 'form', :id => 'edit_survey_1'} do |f|
    - f.inputs t("children_below_three"), :id => "children_below_three", :class => 'step' do
      - unless @survey.child_bellow_3_attending_creche.blank?
        - f.inputs t("reason_for_creche"), :id => "reason_for_creche" do
          = f.input :reason_for_creche_likes, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_free_meal, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_time, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche();"}
          = f.input :reason_for_creche_trust, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_friendships, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_playing, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_learning, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_language, :as => :boolean, :input_html => { :onclick => "max3_reason_for_creche(this);"}
          = f.input :reason_for_creche_other, :input_html => {:style => 'width:650px', :rows => 1 }
          = f.input :reason_for_creche_no_answer, :as => :boolean, :input_html => { :onclick => "reason_for_creche2(this);"}
        = f.input :talk_with_teacher, :as => :radio, :collection => MenuItem.frequency_extended
      - else
        %fieldset{:class => 'inputs'}
          %div
            %span= t('Q101a102under3')
      - unless @survey.child_bellow_3_at_home.blank?
        - f.inputs t("reason_not_attend"), :id => "reason_not_attend" do
          = f.input :reason_not_attend_expensive, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_no_creche, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_no_place, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_no_work, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_no_trust, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_bad_treating, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_language, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_family, :as => :boolean, :input_html => { :onclick => "max3_reason_not_attend(this);"}
          = f.input :reason_not_attend_other, :input_html => {:style => 'width:650px', :rows => 1 }
          = f.input :reason_not_attend_no_answer, :as => :boolean, :input_html => { :onclick => "reason_not_attend2(this);"}
      - else
        %fieldset{:class => 'inputs'}
          %div
            %span= t('Q103under3home')
    = hidden_field_tag "step", "10"

    = render :partial => 'buttons'

app/views/surveys/_form_11.html.haml
#steps
  - semantic_form_for @survey, :html => {:name => 'survey',:class => 'form', :id => 'edit_survey_1'} do |f|
    - f.inputs t("children_below_seven"), :id => "children_below_seven", :class => 'step' do
      - if @survey.child_above_3_below_7_attending_creche.blank?
        %fieldset{:class => 'inputs'}
          %div
            %span= t('Q111-117enrolled')
      - else
        - f.inputs t("reason_for_kindergarten"), :id => "reason_for_kindergarten" do
          = f.input :reason_for_kindergarten_likes, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_free_meal, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_time, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_trust, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_friendships, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_better_chance, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_playing, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_learning, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_language, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_compulsory, :as => :boolean, :input_html => { :onclick => "max3_reason_for_kindergarten(this);"}
          = f.input :reason_for_kindergarten_other, :input_html => {:style => 'width:650px', :rows => 1 }
          = f.input :reason_for_kindergarten_no_answer, :as => :boolean, :input_html => { :onclick => "reason_for_kindergarten2(this);"}
        = f.input :kindergarten_days, :input_html => { :size => 3, :min => 0, :max => 999}
        = f.input :kindergarten_roma, :as => :radio, :collection => MenuItem.roma
        = f.input :class_roma, :as => :radio, :collection => MenuItem.roma
        = f.input :teacher_informs, :as => :radio, :collection => MenuItem.frequency_extended2
        = f.input :lesson_language_understanding, :as => :radio, :collection => MenuItem.language_understanding, :input_html => { :onclick => 'display_switch(this,"57 58 59","survey_teacher_help_input");'}
        = f.input :teacher_help, :as => :radio, :collection => MenuItem.language_difficulties2

      // 11.8
      - if @survey.child_above_3_below_7_not_attending_creche.blank?
        %fieldset{:class => 'inputs'}
          %div
            %span= t('Q118CDFG')
      - else
        - f.inputs t("reason_not_enrolled"), :id => "reason_not_enrolled" do
          / - f.inputs t("reason_not_enrolled"), :id => "reason_not_enrolled" do
          = f.input :reason_not_enrolled_no_like, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_expensive, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_no_clothes, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_no_work, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_trust, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_children_treating, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_not_nearby, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_no_place, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_family, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_language, :as => :boolean, :input_html => { :onclick => "max3_reason_not_enrolled(this);"}
          = f.input :reason_not_enrolled_other, :input_html => {:style => 'width:650px', :rows => 1 }
          = f.input :reason_not_enrolled_no_answer, :as => :boolean, :input_html => { :onclick => "reason_not_enrolled2(this);"}

      // 11.9
      - if @survey.child_above_5_below_7_not_attending_creche.blank?
        %fieldset{:class => 'inputs'}
          %div
            %span= t('Q119–1116notshownFG')
      - else
        = f.input :school_roma, :as => :radio, :collection => MenuItem.roma
        = f.input :school_class_roma, :as => :radio, :collection => MenuItem.roma
        = f.input :school_teacher_information, :as => :radio, :collection => MenuItem.frequency_extended
        = f.input :lesson_difficulty, :as => :radio, :collection => MenuItem.language_understanding, :input_html => { :onclick => 'display_switch(this,"57 58 59","survey_are_teachers_helpfull_input");'}
        = f.input :are_teachers_helpfull, :as => :radio, :collection => MenuItem.frequency_extended
        = f.input :school_good_bad, :as => :radio, :collection => MenuItem.good_bad
        = f.input :test_before_school, :as => :radio, :collection => MenuItem.classic, :input_html => { :onclick => 'display_switch(this,"31 33","survey_test_before_school_result_input");'}

        // 11.16
        = f.input :test_before_school_result, :as => :radio, :collection => MenuItem.test_result, :input_html => { :onclick => 'display_switch(this,"122","survey_test_before_school_other_fieldset");'}

        %fieldset.inputs#survey_test_before_school_other_fieldset{ :style => @survey.test_before_school_result==122 ? "display:;" : "display:none;"}
          %ol
            = f.input :test_before_school_other, :input_html => {:style => 'width:650px', :rows => 1 }

    = hidden_field_tag "step", "11"

    = render :partial => 'buttons'

app/views/surveys/_form_6.html.haml
#steps
  - semantic_form_for @survey, :html => {:name => 'survey',:class => 'form', :id => 'edit_survey_1'} do |f|
    - f.inputs t("6 Parent's attitude"), :id => "parents_attitude", :class => 'step' do
      = f.input :better_in_school, :as => :radio, :collection => MenuItem.better_in_school
      = f.input :kindergarten_importance, :as => :radio, :collection => MenuItem.importance
      = hidden_field_tag "step", "6"

      = render :partial => 'buttons'

app/views/surveys/index.html.haml
- unless @incomplete_surveys.blank?
  - if ['L','LDB','A'].include? current_user.category
    %h1= t('Household Surveys - Incomplete')

    %table{:width => '980px'}
      %tr
        %th{:width => '200px'}= t('Survey No')
        %th{:width => '290px'}= t('Family')
        %th{:width => '260px'}= t('Children')
        %th{:width => '230px'}= t('Date')
      %tr
        %td{:colspan => 4}
          %hr

      - @incomplete_surveys.each do |survey|
        %tr
          %td
            - if current_user.id == survey.created_by or current_user.category == 'A'
              = link_to(survey.number, edit_survey_path(survey))
            - else
              = survey.number
          %td
            / - unless ['C','REF','ME'].include? current_user.category
            / = link_to survey.family.family_name, survey.family unless survey.family.blank?
            / - else
            - if current_user.category == 'A'
              = link_to survey.family.family_name, edit_family_profile_path(survey.family) unless survey.family.blank?
            - else
              = survey.family.family_name  unless survey.family.blank?
          %td
            - unless survey.children.blank?
              %ul
                - survey.children.each do |ch|
                  %li
                    - if current_user.category == 'A'
                      = link_to ch.full_name, edit_child_profile_path(ch)
                    - else
                      = ch.full_name
          %td
            %small= "#{survey.date_of_the_interview}" ' - ' "#{survey.mediator.full_name}"
            - if current_user.category == 'L' || current_user.category == 'LDB' 
              %br
              - if survey.marked_for_delete.blank?
                - if survey.created_by == current_user.id
                  = link_to t('Mark for Delete'), '/surveys/' + survey.id.to_s + '/mark_for_delete/', :disable_with => 'loading...'
              - else
                = t("Marked for delete")
                - if survey.created_by == current_user.id || (['L','LDB'].include? current_user.category)
                  %small= link_to t('(Unmark)'), '/surveys/' + survey.id.to_s + '/mark_for_delete/', :disable_with => 'loading...'
                - if current_user.category == 'L'
                  %br
                  = link_to t("Delete"), survey_path(survey), :method => 'delete', :confirm => t('This will delete survey and all of its data')
        %tr
          %td{:colspan => 4}
            %hr

- unless @completed_surveys.blank?
  %h1= t('Completed Household Surveys')

  %table{:width => '980px'}
    %tr
      %th{:width => '200px'}= t('Survey No')
      %th{:width => '290px'}= t('Family')
      %th{:width => '260px'}= t('Children')
      %th{:width => '230px'}= t('Date')
    %tr
      %td{:colspan => 4}
        %hr

    - @completed_surveys.each do |survey|
      %tr
        %td= (['A','L','LDB'].include? current_user.category) ? link_to(survey.number, edit_survey_path(survey)) : survey.number
        %td
          / - unless ['C','REF','ME'].include? current_user.category
          / = link_to survey.family.family_name, survey.family unless survey.family.blank?
          / - else
          - if current_user.category == 'A'
            = link_to survey.family.family_name, edit_family_profile_path(survey.family) unless survey.family.blank?
          - else
            = survey.family.family_name  unless survey.family.blank?
        %td
          - unless survey.children.blank?
            %ul
              - survey.children.each do |ch|
                %li
                  - if current_user.category == 'A'
                    = link_to ch.full_name, edit_child_profile_path(ch)
                  - else
                    = ch.full_name
        %td
          %small= "#{survey.date_of_the_interview}" ' - ' "#{survey.mediator.full_name}"
          - if ['L','LDB'].include? current_user.category
            - if survey.verified == 1
            - else
              - if survey.marked_for_delete.blank?
                - if survey.created_by == current_user.id
                  %br
                  = link_to t('Mark for Delete'), '/surveys/' + survey.id.to_s + '/mark_for_delete/', :disable_with => 'loading...'
              - else
                %br
                = t("Marked for delete")
                - if survey.created_by == current_user.id || (['L','LDB'].include? current_user.category)
                  %small= link_to t('(Unmark)'), '/surveys/' + survey.id.to_s + '/mark_for_delete/', :disable_with => 'loading...'
                - if current_user.category == 'L'
                  %br
                  = link_to t("Delete"), survey_path(survey), :method => 'delete', :confirm => t('This will delete survey and all of its data')
            - if current_user.category == 'L'
              %br
              - if survey.verified == 1
                = t("Verified")
              - else
                = link_to t('Mark as verified'), '/surveys/' + survey.id.to_s + '/mark_as_verified/', :disable_with => 'loading...'
      %tr
        %td{:colspan => 4}
          %hr
%br

.commit
  = link_to t('Add New Household Survey'), new_survey_path

app/views/surveys/new.html.haml
%h1= t("New Survey")

#navigation
  %ul
    %li{ :class => params[:step]=='1' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=1'} 1 & 2
      %p 1 & 2

    %li{ :class => params[:step]=='2' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=2'} 3
      %p 3

    %li{ :class => params[:step]=='3' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=3'} 4
      / %li
      /   %a{ :href => edit_survey_path(@survey) + '?step=4'} 4
      %p 4

    %li{ :class => params[:step]=='5' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=5'} 5
      %p 5

    %li{ :class => params[:step]=='6' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=6'} 6
      %p 6

    %li{ :class => params[:step]=='7' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=7'} 7
      %p 7

    %li{ :class => params[:step]=='8' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=8'} 8
      %p 8

    %li{ :class => params[:step]=='9' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=9'} 9
      %p 9

    %li{ :class => params[:step]=='10' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=10'} 10
      %p 10

    %li{ :class => params[:step]=='11' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=11'} 11
      %p 11

    %li{ :class => params[:step]=='12' ? 'selected' : ''}  
      / %a{ :href => edit_survey_path(@survey) + '?step=12'} 12
      %p 12

- if params[:action] == 'new'
  = render 'form_1'
- else
  = render 'form_'+params[:step]

/ = render 'form_' + @step.to_s
/ - if @survey.current_step==2
/   = render 'form_2'
/ - elsif @survey.current_step==3
/   = render 'form_3'
/ - elsif @survey.current_step==4
/   = render 'form'
/ - else
/   = render 'form'

.commit
  = link_to t('Back'), surveys_path

/ - if params[:step]=='1'
/   = render 'form_1'
/ - elsif !@survey.errors.blank?
/   = render 'form_1'
/ - else
/   = render 'form'

app/views/surveys/show.html.haml
.show
  %p#notice= notice


  = link_to t('Edit'), edit_survey_path(@survey)
  \|
  = link_to t('Back'), surveys_path